name: Video Stream

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main'
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes to ensure it's active

jobs:
  stream:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Debug System Resources
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h

      - name: Debug - List Repo Files
        run: ls -la

      - name: Debug - Check stream.py
        run: cat stream.py || echo "stream.py not found!"

      - name: Run Stream Script
        run: |
          while true; do
            python stream.py || echo "Script crashed. Restarting..."
            sleep 3  # Wait 3 seconds before restarting
          done
