name: Video Stream

on:
  push:
    branches:
      - main  # Runs when pushing to 'main'
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  stream:
    runs-on: ubuntu-latest
    concurrency:
      group: video-stream  # Ensures only one instance runs at a time
      cancel-in-progress: true  # Cancels the previous run before starting a new one

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install ffmpeg-python
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Stream Script
        run: |
          while true; do
            python stream.py || echo "Script crashed. Restarting..."
            sleep 3  # Wait 3 seconds before restarting
          done
