name: Stream Movies

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual start

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  stream:
    needs: cancel-previous
    runs-on: ubuntu-latest
    timeout-minutes: 0  # Disables timeout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg mpv

      - name: Run Movie Streaming Script
        run: |
          while true; do
            python3 stream_mpd.py
            sleep 5
          done
